
DROP SCHEMA public CASCADE;
CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS public.User;
DROP TABLE IF EXISTS public.Like;
DROP TABLE IF EXISTS public.Friendship;


CREATE TABLE IF NOT EXISTS public."User"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
    name varchar(255)  ,
    surname varchar(255) ,
    birthdate date,
    CONSTRAINT "User_PK" PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public."Likes"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
    post_id bigint,
    user_id bigint,
    timestamp timestamp without time zone,
    CONSTRAINT "likes_PK" PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public."Friendship"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 1),
    user_id1 bigint,
    user_id2 bigint,
    timestamp timestamp without time zone,
    CONSTRAINT "friendship_PK" PRIMARY KEY (id)
)
