spring:
  application:
    name: security_secret
  profiles:
    active: dev

server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: root
    schema : classpath:/data.sql


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      mode : always

mybatis:
  config-location: "classpath:mybatis-config.xml"

---
spring:
  config:
    activate.on-profile : docker

server:
  port: 8082

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.111:5432/security
    username: postgres
    password: root

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  config-location: "classpath:mybatis-config.xml"