version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: postgres_name
    ports:
      - 5432:5432
    volumes:
      - app_data_volumes:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: root
    restart: always

  secret:
    image: itdarashukd/secret:latest
    container_name: secret
    ports:
      - 8082:8082
    restart: unless-stopped
    volumes:
      - ./docker_data/secret/data:/secret/data
    environment:
      url: jdbc:postgresql://db:5432/security
    depends_on:
      - db

volumes:
  app_data_volumes:
